name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  pytest:
    name: "Pytest"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v7"

      - name: "Set up Python"
        uses: "actions/setup-python@v7"
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install Poetry"
        run: python3 -m pip install poetry==2.3.3

      - name: "Configure poetry"
        run: python3 -m poetry config virtualenvs.in-project true

      - name: "Cache the virtualenv"
        uses: "actions/cache@v6"
        with:
          path: ./.venv
          key: ${{ runner.os }}-test-venv-${{ hashFiles('**/poetry.lock') }}

      - name: "Install requirements"
        run: python3 -m poetry install --with test

      - name: "Run"
        run: python3 -m poetry run pytest
